# Fos Rest Bundle
fos_rest:
    versioning: true
    body_listener: true
    format_listener: true
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    serializer:
        serialize_null: true
    routing_loader:
        default_format: json
    zone:
        - { path: ^/([a-z]+)/api/* }
    view:
        formats:
            json: true
            xml: true
        view_response_listener: 'force'
        failed_validation: HTTP_BAD_REQUEST
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true