nelmio_api_doc:
    documentation:
        info:
            title: Katye Pwop
            description: Une application pour maintenir les quartiers propres!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/{_locale}/api/{version} # Accepts routes under /api except /api/doc
