vich_uploader:
    db_driver: orm
    mappings:
        profile_image:
            inject_on_load: true
            delete_on_remove: true
            delete_on_update: true
            namer: vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/profile
            upload_destination: '%kernel.project_dir%/public/uploads/images/profile'
        message_image:
            inject_on_load: true
            delete_on_remove: true
            delete_on_update: true
            namer: vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/message
            upload_destination: '%kernel.project_dir%/public/uploads/images/message'
