admin_controllers:
    resource: '../../src/Controller/SuperAdmin'
    type:     annotation
    prefix: /admin

manage_controllers:
    resource: '../../src/Controller/Admin'
    type:     annotation
    prefix: /manage

frontend_controllers:
    resource: '../../src/Controller/Frontend'
    type:     annotation

api_controller:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api
